"""Extract match info and both squads from an FRF (Football Connect) referee report PDF.

The report is generated by iTextSharp with a proper text layer, so everything is read
from text and coordinates -- no OCR involved.

Layout notes that drive the parsing below (verified against a sample report):

* Page 1 ("Raport Arbitru") carries the labelled match fields: Competitia, Data, Ora,
  Etapa and the "Rezultat partida" scoreline.
* Every squad page ("Foaie de meci") has a footer naming the club and its side,
  e.g. "Foaie de meci, club gazde: SC Dinamo 1948" (gazde = home, oaspeti = away).
* Inside a squad page each player spans three stacked text lines:

      surname                <- name column, ~5pt above
      number   [P] [C]       <- number column (x < 60), plus GK / captain markers
      given names            <- name column, ~5pt below

Each player is returned as a dict: number, name, gk, captain. The gk / captain flags
come from the report's own markers; the Hudl template has no column for them, so they
are rendered as a "(GK)" / "(C)" suffix on the name (see fill_teamsheet.py).
"""

import re

import pdfplumber

# Column geometry, in PDF points from the left edge of the page.
NUMBER_MAX_X = 60.0          # shirt-number column
NAME_MIN_X, NAME_MAX_X = 140.0, 425.0   # "Nume prenume"; excludes Foto and Info personal

# Marker glyphs on the shirt-number line. The x-bands matter: a second "(c)" glyph sits
# at x0 ~ 393 in the "generata cu Football Connect (c)" footer of every page, so the
# glyph alone is not enough to identify a captain.
GK_GLYPH, CAPTAIN_GLYPH = "℗", "©"
GK_MAX_X = 75.0
CAPTAIN_MIN_X, CAPTAIN_MAX_X = 75.0, 110.0

LINE_TOLERANCE = 2.5         # words within this many points share a line
ROW_SPAN = 14.0              # max gap between a number and its surname / given-name line

SECTION_HEADERS = ("Titulari", "Rezerve", "Jucători", "Banca")
PLAYER_SECTIONS = ("Titulari", "Rezerve")

# Tokens that live in the right-hand "Info personal" column.
INFO_TOKEN = re.compile(r"^(născut|FIFA|ID:|\d{2}\.\d{2}\.\d{4})", re.IGNORECASE)


class ParseError(Exception):
    """The PDF did not look like an FRF referee report.

    Carries a machine-readable `code` (and optional `sides`) so the UI can show a
    localized message, while `str()` stays a useful Romanian message on its own.
    """

    def __init__(self, message, code=None, sides=None):
        super().__init__(message)
        self.code = code
        self.sides = sides or []


def _group_lines(words):
    """Cluster extracted words into lines by their vertical position."""
    lines = []
    for word in sorted(words, key=lambda w: (w["top"], w["x0"])):
        if lines and abs(lines[-1]["top"] - word["top"]) <= LINE_TOLERANCE:
            lines[-1]["words"].append(word)
        else:
            lines.append({"top": word["top"], "words": [word]})
    for line in lines:
        line["words"].sort(key=lambda w: w["x0"])
    return lines


def _name_text(line):
    """The "Nume prenume" portion of a line, or "" if it holds no name."""
    parts = [
        w["text"]
        for w in line["words"]
        if NAME_MIN_X <= w["x0"] < NAME_MAX_X and not INFO_TOKEN.match(w["text"])
    ]
    return " ".join(parts).strip()


def _section_of(top, bands):
    """Name of the section a line at `top` belongs to (bands are sorted by top)."""
    current = None
    for band_top, name in bands:
        if band_top <= top:
            current = name
        else:
            break
    return current


def _squad_page(page, squads):
    """Read one "Foaie de meci" page into `squads`, keyed by side."""
    text = page.extract_text() or ""
    home = re.search(r"club\s+gazde\s*:\s*(.+)", text)
    away = re.search(r"club\s+oaspe\w*\s*:\s*(.+)", text)
    if home:
        side, club = "home", home.group(1)
    elif away:
        side, club = "away", away.group(1)
    else:
        return

    squad = squads.setdefault(side, {"name": club.strip(), "starters": [], "subs": []})

    lines = _group_lines(page.extract_words())
    bands = sorted(
        (line["top"], word["text"])
        for line in lines
        for word in line["words"]
        if word["x0"] < NUMBER_MAX_X and word["text"] in SECTION_HEADERS
    )

    for index, line in enumerate(lines):
        numbers = [
            w["text"]
            for w in line["words"]
            if w["x0"] < NUMBER_MAX_X and w["text"].isdigit()
        ]
        if not numbers:
            continue
        section = _section_of(line["top"], bands)
        if section not in PLAYER_SECTIONS:
            continue

        surname = given = ""
        if index > 0 and line["top"] - lines[index - 1]["top"] <= ROW_SPAN:
            surname = _name_text(lines[index - 1])
        if index + 1 < len(lines) and lines[index + 1]["top"] - line["top"] <= ROW_SPAN:
            given = _name_text(lines[index + 1])

        name = re.sub(r"\s+", " ", f"{surname} {given}").strip()
        if not name or name == "-":
            continue

        bucket = "starters" if section == "Titulari" else "subs"
        squad[bucket].append(
            {
                "number": int(numbers[0]),
                "name": name,
                "gk": any(
                    w["text"] == GK_GLYPH and w["x0"] < GK_MAX_X for w in line["words"]
                ),
                "captain": any(
                    w["text"] == CAPTAIN_GLYPH and CAPTAIN_MIN_X <= w["x0"] < CAPTAIN_MAX_X
                    for w in line["words"]
                ),
            }
        )


def _match_info(page):
    text = page.extract_text() or ""

    competition = re.search(r"Competitia\s*:\s*(.+?)(?:\s+Data\s*:|$)", text, re.MULTILINE)
    date = re.search(r"Data\s*:\s*(\d{2})\.(\d{2})\.(\d{4})", text)
    score = re.search(r"Rezultat\s+partid[ăa]\s*\n\s*(\d+)\s*-\s*(\d+)", text)

    if not date:
        raise ParseError(
            "Nu am găsit data meciului (câmpul 'Data:') în raport. "
            "Verifică dacă ai încărcat raportul de arbitraj din www.footballconnect.ro.",
            code="no_date",
        )

    day, month, year = date.groups()
    return {
        "competition": competition.group(1).strip() if competition else "",
        "date": f"{day}/{month}/{year}",
        "date_iso": f"{year}-{month}-{day}",
        "score": f"{score.group(1)}-{score.group(2)}" if score else "",
    }


def parse(file_like):
    """Parse a referee report PDF into match info plus both squads."""
    with pdfplumber.open(file_like) as pdf:
        if not pdf.pages:
            raise ParseError("PDF-ul este gol.", code="empty_pdf")

        info = _match_info(pdf.pages[0])

        squads = {}
        for page in pdf.pages:
            if "Foaie de meci" in (page.extract_text() or ""):
                _squad_page(page, squads)

    missing = [side for side in ("home", "away") if side not in squads]
    if missing:
        sides = ", ".join("gazde" if s == "home" else "oaspeți" for s in missing)
        raise ParseError(
            f"Nu am găsit foaia de meci pentru: {sides}. "
            "Verifică dacă ai încărcat raportul complet de arbitraj din "
            "www.footballconnect.ro (care include ambele echipe), "
            "nu foaia de meci a unei singure echipe.",
            code="missing_sides",
            sides=missing,
        )

    info["home"] = squads["home"]
    info["away"] = squads["away"]
    return info


if __name__ == "__main__":
    import json
    import sys

    sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(parse(sys.argv[1]), ensure_ascii=False, indent=1))
